#pragma once

#define MAX_CELL_MARKER     5
#define TABLESIZE           8
#define TABLE_RENDER_SIZE   320
#define CELL_RENDER_SIZE    TABLE_RENDER_SIZE / TABLESIZE

#define SPEED_ANIMATION     1

#define CELL_SELECTED_COLOR 0xAA0000
#define CELL_DESTROY_COLOR  0x00AA00
#define CELL_BACK_COLOR     0x0000AA