#pragma once

#define MAX_CELL_MARKER     5
#define TABLESIZE           8
#define TABLE_RENDER_SIZE   320
#define CELL_RENDER_SIZE    TABLE_RENDER_SIZE / TABLESIZE

#define CELL_SELECTED_COLOR 0xAA0000